### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by uli22** [githubharald/WordDetectorNN#21]
On trying to get the code running I get the following error:

Traceback (most recent call last):
  File "c:\Users\Mein PC\Documents\PY_work\HTRPipeline\WordDetectorNN-master\src\infer.py", line 37, in <module>
    main()
  File "c:\Users\Mein PC\Documents\PY_work\HTRPipeline\WordDetectorNN-master\src\infer.py", line 24, in main
    net.to(args.device)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\Mein PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Is there a way to run the model on windows without CUDA?
I would like to use the model for segmenting historical geman texts from about 1570 - 1650
Thanks in advance

**Comment by githubharald** [comment]
Hi, how did you run the script, did you provide the cpu command line parameter?
https://github.com/githubharald/WordDetectorNN/blob/master/src/infer.py#L14

If you specify --device cpu it should work also on a computer without GPU.

**Comment by uli22** [comment]
Thanks for answering.
I run the script from vscode and did not change default cuda to cpu in line
19.
sorry for that. Now it is running as expected.
cheers
Uli


Am Mo., 3. Juli 2023 um 09:22 Uhr schrieb Harald Scheidl <
***@***.***>:

**Comment by githubharald** [comment]
sounds good!
