### ISSUE TITLE
infer.py RuntimeError weights is a zip archive

### ISSUE THREAD

**Issue by seekingdeep** [githubharald/WordDetectorNN#9]
```
(calamari) home@home-lnx:~/programs/WordDetectorNN/src$ python infer.py 
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: '_tensor_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 33, in <module>
    main()
  File "infer.py", line 18, in main
    net.load_state_dict(torch.load('../model/weights', map_location=args.device))
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/home/anaconda3/envs/calamari/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: ../model/weights is a zip archive (did you mean to use torch.jit.load()?)
```

**Comment by seekingdeep** [comment]
solved by installing newer versions of the requirements
